/**
 * Import the utility AzureGraph
 */
const AzureGraph = require('../../utils/AzureGraph');

const accessToken = 'eyJ0eXAiOiJKV1QiLCJub25jZSI6IjhjV0VSTXMyc3Zzd1ZLbGhEMjF6RktjVTNRS3hlV2NjZUhQTzZuNnRCejgiLCJhbGciOiJSUzI1NiIsIng1dCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSIsImtpZCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9kZWNlMjE0NS05ZmZhLTQ4YWYtYjE0ZS1kZDNhZGU2MmE1NTYvIiwiaWF0IjoxNjYyNjQyNTY5LCJuYmYiOjE2NjI2NDI1NjksImV4cCI6MTY2MjY0NjQ2OSwiYWlvIjoiRTJaZ1lMRDFtczR5bjNuUjY5b0lzWFh6Si9Eb0F3QT0iLCJhcHBfZGlzcGxheW5hbWUiOiJ0ZXN0LWV2b25payIsImFwcGlkIjoiMmIzMTA4ODgtYWZlZi00NDgxLWI5NmYtMzZiYjg0N2NjYzQwIiwiYXBwaWRhY3IiOiIxIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvZGVjZTIxNDUtOWZmYS00OGFmLWIxNGUtZGQzYWRlNjJhNTU2LyIsImlkdHlwIjoiYXBwIiwib2lkIjoiMDgxODM4NTktMmYxYy00OTA1LWE0MTctNjI0YzgzMjk2ODZjIiwicmgiOiIwLkFXQUFSU0hPM3ZxZnIwaXhUdDA2M21LbFZnTUFBQUFBQUFBQXdBQUFBQUFBQUFCaEFBQS4iLCJyb2xlcyI6WyJBcHBsaWNhdGlvbi5SZWFkV3JpdGUuT3duZWRCeSIsIlVzZXJBdXRoZW50aWNhdGlvbk1ldGhvZC5SZWFkV3JpdGUuQWxsIiwiUm9sZU1hbmFnZW1lbnQuUmVhZC5EaXJlY3RvcnkiLCJBcHBsaWNhdGlvbi5SZWFkV3JpdGUuQWxsIiwiRGlyZWN0b3J5LlJlYWRXcml0ZS5BbGwiLCJEaXJlY3RvcnkuUmVhZC5BbGwiLCJSb2xlTWFuYWdlbWVudC5SZWFkLkFsbCIsIlVzZXIuUmVhZC5BbGwiLCJSb2xlTWFuYWdlbWVudC5SZWFkV3JpdGUuQ2xvdWRQQyIsIlJvbGVNYW5hZ2VtZW50LlJlYWRXcml0ZS5EaXJlY3RvcnkiLCJBcHBsaWNhdGlvbi5SZWFkLkFsbCJdLCJzdWIiOiIwODE4Mzg1OS0yZjFjLTQ5MDUtYTQxNy02MjRjODMyOTY4NmMiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiRVUiLCJ0aWQiOiJkZWNlMjE0NS05ZmZhLTQ4YWYtYjE0ZS1kZDNhZGU2MmE1NTYiLCJ1dGkiOiJiMkZndjZLR1FVU25BNk44QlVsMkFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyIwOTk3YTFkMC0wZDFkLTRhY2ItYjQwOC1kNWNhNzMxMjFlOTAiXSwieG1zX3RjZHQiOjE1ODk1MzM5NTcsInhtc190ZGJyIjoiRVUifQ.pRGqQxzxGSKGa_GLPRRh9mo7iWDqVwp6oQiYtzjKpravoGfC8YQfeAOitaO0ySgP0UiKtcXGPkawGG0P5JC0VmdkB6ObFJU6jhhRHu-NImSS-26Vm4Wvlk6wQcHW_RX03mUQANxzvW2zLWmJBtAvNsNrqpAVTf12at0R-U17CdD2s9M-o8JjW4Wk5UB9TwFMizMnHEd-grxUnHLU26p7HFaDYrxnTowDMIQ9T4wBST9dU1xDwvJsYTqDKBC19RU8XymcaJ0kyB3jOxtRbBenTBP54Azb4HPS8Nwz7jhacTYH-_ifKmldVoPp7XBIBo8osV-Xp7h4bGWXhRTVjrVoNw';
const reference = 'applications/';

/**
 * Is possible to define a list di calls async to retrieve the data from the reference name
 */
const getOwnersRoleAppAdmin = async () => {
    const endpoint = `${reference}${process.env.AZURE_APPLICATION_ID}/owners`;
    return await AzureGraph.getApi(endpoint, accessToken)
        .then((response) => {
            return response;
        })
        .catch((error) => {
            throw error;
        })
}

module.exports = { getOwnersRoleAppAdmin };